os:
  - osx

osx_image: xcode7.3

language: node_js

node_js:
  # The version of electron we us ships with Node v5.10.0, try to match it
  - 5.10

before_install:
  # The version of electron we use ships with Node v5.10.0, match it
  - nvm install 5.10.0
  # Headless browser testing for electron app
  - export DISPLAY=":99.0"
  - sudo xvfb :99 -ac -screen 0 1024x1024x16 &
  # Wait for xvfb to fully come up, also gives us a chance to capture the
  # output of xvfb cleanly through the travis ui in case of an error since we
  # are running the tool in the background
  - sleep 3
  # We need wine to build the windows binaries
  - wget https://dl.winehq.org/wine-builds/macosx/i686/winehq-staging-1.9.16.pkg
  - sudo installer -pkg ./winehq-staging-*.pkg -target /

after_success:
  - find / -type f -name 'wine'
  - export PATH="/Applications/Wine Staging.app/Contents/MacOS/wine":$PATH
  - wine --help
  # Build all packages
  - node bin/package.js
