os:
  - osx

osx_image: xcode7.3

before_script:
  - wget https://distfiles.macports.org/MacPorts/MacPorts-2.3.4-10.11-ElCapitan.pkg
  - sudo installer -pkg MacPorts-2.3.4-10.11-ElCapitan.pkg -target /
  - export PATH=/opt/local/bin:/opt/local/sbin:$PATH
  - sudo port selfupdate
  - sudo port install firefox-x11
