nstallos:
  - osx

osx_image: xcode7.3

language: node_js

node_js:
  - 5.10

before_install:
  - brew update
  - brew tap caskroom/cask
  - brew cask install java xquartz
  - brew install wine
  - export DISPLAY=":99.0"
  - sudo xvfb :99 -ac -screen 0 1024x1024x16 &
  - sleep 3

after_success:
  - node bin/package.js
