os:
  - osx

osx_image: xcode7.3

language: node_js

node_js:
  - 5.10

before_install:
  - export DISPLAY=":99.0"
  - sudo xvfb :99 -ac -screen 0 1024x1024x16 &
  - sleep 3

after_success:
  - node bin/package.js

after_failure:
  - find build -type f
